/**
 * Super-spec tests (todo 800) — specs/super-spec.json, generated by
 * scripts/build-super-spec.mjs (npm run spec:build).
 *
 * Covers: build determinism (byte-identical across runs, and the checked-in
 * artifact is current), per-service operation counts, policy consistency
 * with catalog/manifest.json (single source of truth for the deny-list),
 * callable-name consistency (every cataloged operation appears as an
 * operationId), the judicious skills representation (3 ops + embedded index,
 * NOT one path per skill/section), and the size budget the design doc
 * records (the compact form ships into a sandbox on every search).
 */
import { describe, expect, it } from "vitest";
import { execFileSync } from "node:child_process";
import { readFileSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
const SPEC_PATH = join(ROOT, "specs", "super-spec.json");

type Operation = {
  operationId: string;
  summary?: string;
  description?: string;
  tags?: string[];
  requestBody?: { content?: Record<string, { schema?: Record<string, unknown> }> };
  "x-service": string;
  "x-policy": { allow: boolean; denyReason: string | null };
  "x-cost": string;
  "x-auth": string;
  "x-execute"?: string;
  "x-algolia"?: unknown;
  "x-skill-index"?: Array<{ id: string; source: string; description: string; sections: string[] }>;
};

const spec = JSON.parse(readFileSync(SPEC_PATH, "utf8")) as {
  openapi: string;
  info: Record<string, unknown>;
  paths: Record<string, Record<string, Operation>>;
  components: Record<string, Record<string, unknown>>;
  "x-services": Record<string, unknown>;
};

const manifest = JSON.parse(readFileSync(join(ROOT, "catalog", "manifest.json"), "utf8")) as {
  entries: Array<{
    id: string;
    service: string;
    kind: string;
    policy: { allow: boolean; denyReason: string | null };
  }>;
};

function allOps(): Array<[string, string, Operation]> {
  const out: Array<[string, string, Operation]> = [];
  for (const [path, item] of Object.entries(spec.paths)) {
    for (const [method, op] of Object.entries(item)) out.push([path, method, op]);
  }
  return out;
}

describe("build determinism", () => {
  it("the checked-in artifact is current, and two rebuilds are byte-identical", () => {
    const before = readFileSync(SPEC_PATH);
    execFileSync("node", [join(ROOT, "scripts", "build-super-spec.mjs")], { cwd: ROOT });
    const first = readFileSync(SPEC_PATH);
    execFileSync("node", [join(ROOT, "scripts", "build-super-spec.mjs")], { cwd: ROOT });
    const second = readFileSync(SPEC_PATH);
    expect(first.equals(second)).toBe(true);
    expect(before.equals(first), "specs/super-spec.json is stale — run npm run spec:build").toBe(
      true
    );
  });
});

describe("shape and counts", () => {
  it("is an OpenAPI-3.1-style doc with the four service tags", () => {
    expect(spec.openapi).toBe("3.1.0");
    expect(Object.keys(spec["x-services"]).sort()).toEqual([
      "lumenloop",
      "scout",
      "skills",
      "stellarDocs"
    ]);
  });

  it("has the expected per-service operation counts", () => {
    const counts: Record<string, { total: number; allowed: number }> = {};
    for (const [, , op] of allOps()) {
      counts[op["x-service"]] ??= { total: 0, allowed: 0 };
      counts[op["x-service"]]!.total += 1;
      if (op["x-policy"].allow) counts[op["x-service"]]!.allowed += 1;
    }
    // lumenloop: 21 cataloged tools (20 allowed; request_research denied) +
    // 15 account/discovery endpoints, all denied.
    expect(counts.lumenloop).toEqual({ total: 36, allowed: 20 });
    // scout: 24 upstream ops, 3 denied (feedback write, submit-listing, assistant).
    expect(counts.scout).toEqual({ total: 24, allowed: 21 });
    expect(counts.stellarDocs).toEqual({ total: 12, allowed: 12 });
    expect(counts.skills).toEqual({ total: 3, allowed: 3 });
  });

  it("every path is '/{service}/{operation}' and operationIds are unique callable ids", () => {
    const seen = new Set<string>();
    for (const [path, , op] of allOps()) {
      expect(path.startsWith(`/${op["x-service"]}/`), path).toBe(true);
      expect(seen.has(op.operationId), `duplicate ${op.operationId}`).toBe(false);
      seen.add(op.operationId);
      expect(op.tags?.[0]).toBe(op["x-service"]);
    }
  });

  it("allowed ops carry an exact x-execute call line; denied ops carry none", () => {
    for (const [, , op] of allOps()) {
      if (op["x-policy"].allow) {
        expect(op["x-execute"], op.operationId).toBeTruthy();
      } else {
        expect(op["x-execute"], op.operationId).toBeUndefined();
        expect(op["x-policy"].denyReason, op.operationId).toBeTruthy();
      }
    }
    // Service ops are called as `await <operationId>(args)`.
    for (const [, , op] of allOps()) {
      if (op["x-execute"] && op["x-service"] !== "skills") {
        expect(op["x-execute"]).toBe(`await ${op.operationId}(args)`);
      }
    }
  });
});

describe("consistency with the catalog (single source of truth)", () => {
  it("every cataloged operation id appears as an operationId with the SAME policy", () => {
    const byOperationId = new Map(allOps().map(([, , op]) => [op.operationId, op]));
    const catalogOps = manifest.entries.filter((e) => e.kind === "operation");
    expect(catalogOps.length).toBe(21 + 24 + 12);
    for (const entry of catalogOps) {
      const op = byOperationId.get(entry.id);
      expect(op, `catalog op ${entry.id} missing from super spec`).toBeDefined();
      expect(op!["x-policy"], entry.id).toEqual(entry.policy);
    }
  });

  it("the skills index matches the catalog's exposed (allowed) skills and its section slugs resolve", () => {
    const index = spec.paths["/skills/list_skills"]!.get!["x-skill-index"]!;
    // Policy-aware: the index advertises only allowed skills — the 7 retired
    // Lumenloop onboarding skills are deny-listed and must not appear here.
    const catalogSkillIds = manifest.entries
      .filter((e) => e.service === "skills" && e.kind === "skill" && e.policy.allow)
      .map((e) => e.id)
      .sort();
    expect(index.map((s) => s.id)).toEqual(catalogSkillIds);
    expect(index).toHaveLength(18);

    // Heading-list-only index: every listed section corresponds to a cataloged
    // skill-section entry (file:… keys verbatim; headings via the shared slug).
    const sectionIds = new Set(
      manifest.entries.filter((e) => e.kind === "skill-section").map((e) => e.id)
    );
    const slugify = (text: string) =>
      text
        .toLowerCase()
        .replace(/[^a-z0-9]+/g, "-")
        .replace(/^-+|-+$/g, "") || "section";
    let checked = 0;
    for (const skill of index) {
      const used = new Set<string>();
      for (const section of skill.sections) {
        let key: string;
        if (section.startsWith("file:")) {
          key = section;
        } else {
          let slug = slugify(section);
          for (let n = 2; used.has(slug); n++) slug = `${slugify(section)}-${n}`;
          used.add(slug);
          key = slug;
        }
        expect(sectionIds.has(`${skill.id}#${key}`), `${skill.id}#${key}`).toBe(true);
        checked += 1;
      }
    }
    expect(checked).toBe(203); // every cataloged section is discoverable in the index (post-retirement)
  });

  it("read_skill's name enum is exactly the 25 real skill ids", () => {
    const schema = spec.paths["/skills/read_skill"]!.post!.requestBody!.content![
      "application/json"
    ]!.schema as { properties: { name: { enum: string[] } } };
    const index = spec.paths["/skills/list_skills"]!.get!["x-skill-index"]!;
    expect(schema.properties.name.enum).toEqual(index.map((s) => s.id));
  });
});

describe("service specifics", () => {
  it("stellarDocs ops keep the algolia mapping as a vendor extension", () => {
    const docsOps = allOps().filter(([, , op]) => op["x-service"] === "stellarDocs");
    for (const [, , op] of docsOps) {
      expect(op["x-algolia"], op.operationId).toBeDefined();
    }
    const backend = (spec["x-services"].stellarDocs as { backend: { type: string } }).backend;
    expect(backend.type).toBe("algolia");
  });

  it("scout $refs resolve within the merged doc (namespaced components)", () => {
    const refs = JSON.stringify(spec.paths).match(/"\$ref":"([^"]+)"/g) ?? [];
    expect(refs.length).toBeGreaterThan(0);
    for (const raw of refs) {
      const ref = raw.slice('"$ref":"'.length, -1);
      expect(ref.startsWith("#/components/"), ref).toBe(true);
      const [, , group, name] = ref.split("/");
      expect(
        (spec.components[group!] as Record<string, unknown>)[name!],
        `unresolvable ${ref}`
      ).toBeDefined();
    }
  });

  it("lumenloop tool descriptions carry when_to_use/returns; request_research stays denied metered", () => {
    const searchDirectory = spec.paths["/lumenloop/search_directory"]!.post!;
    expect(searchDirectory.description).toContain("When to use:");
    expect(searchDirectory.description).toContain("Returns:");
    const research = spec.paths["/lumenloop/request_research"]!.post!;
    expect(research["x-cost"]).toBe("metered");
    expect(research["x-policy"].allow).toBe(false);
  });
});

describe("size budget (design doc §4)", () => {
  it("the compact form that ships into each search sandbox stays under 300 KB", () => {
    const compact = Buffer.byteLength(JSON.stringify(spec), "utf8");
    expect(compact).toBeLessThan(300 * 1024);
  });
});
