/**
 * Regenerate src/og.ts — the 1200x630 social-preview image served at /og.png.
 *
 *   node scripts/gen-og.mjs   (or: npm run site:og)
 *
 * Requires ImageMagick (`magick`) on PATH. Mirrors the landing hero: an
 * authentic 4x4 Bayer ordered-dither orange globe (matching src/site.ts's WebGL
 * shader) on the left, editorial type (IBM Plex Serif / Plex Sans / Plex Mono,
 * fetched from google/fonts) set on the right. Deterministic — never
 * hand-edit src/og.ts, rerun this instead.
 */
import { execFileSync } from "node:child_process";
import { mkdtempSync, writeFileSync, readFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const work = mkdtempSync(join(tmpdir(), "raven-og-"));
const p = (f) => join(work, f);

async function download(url, dest) {
  const res = await fetch(url);
  if (!res.ok) throw new Error(`download failed ${res.status} ${res.statusText}: ${url}`);
  const buf = Buffer.from(await res.arrayBuffer());
  writeFileSync(dest, buf);
}
const magick = (args) => execFileSync("magick", args, { stdio: ["ignore", "ignore", "inherit"] });

const SERIF = p("PlexSerif.ttf");
const SANS = p("PlexSans.ttf");
const MONO = p("PlexMono.ttf");
await download("https://github.com/google/fonts/raw/main/ofl/ibmplexserif/IBMPlexSerif-Bold.ttf", SERIF);
await download("https://github.com/google/fonts/raw/main/ofl/ibmplexsans/IBMPlexSans%5Bwdth,wght%5D.ttf", SANS);
await download("https://github.com/google/fonts/raw/main/ofl/ibmplexmono/IBMPlexMono-Regular.ttf", MONO);

const RAVEN = "path 'M2 14 C8 13 10 9 12 4 C14 9 16 13 22 14 C16 14 13 16 12 20 C11 16 8 14 2 14 Z'";

// 1) grayscale sphere as a lower-left corner arc; a light (not white) core keeps
//    dither texture everywhere (never a flat solid fill), like the live sphere
magick(["-size", "1200x630", "-define", "gradient:center=120,720", "-define", "gradient:radii=560,560",
  "radial-gradient:#cfcfcf-black", p("sphere_gray.png")]);
// 2) 4x4 Bayer ordered dither -> black/white dots
magick([p("sphere_gray.png"), "-ordered-dither", "o4x4", p("sphere_mask.png")]);
// 3) orange globe on deep-green via the dither mask
magick(["-size", "1200x630", "xc:#0e150d", "(", "-size", "1200x630", "xc:#ff5500", ")",
  p("sphere_mask.png"), "-composite", p("globe.png")]);
// 4) legibility scrim: dark radial pocket over the copy (right) + top band
magick([p("globe.png"),
  "(", "-size", "1200x630", "-define", "gradient:center=880,320", "-define", "gradient:radii=700,600",
  "radial-gradient:#0e150dF2-#0e150d00", ")", "-composite",
  "(", "-size", "1200x150", "gradient:#0e150dCC-#0e150d00", ")", "-geometry", "+0+0", "-composite",
  p("og_base.png")]);
// 5) type — right column (x≈600), editorial faces, title stacked on two lines
const RX = 600;
magick([p("og_base.png"),
  "-fill", "#ff5500", "-draw", `translate 600,42 scale 1.15,1.15 ${RAVEN}`,
  "-font", SANS, "-weight", "600", "-pointsize", "22", "-fill", "#9aa890", "-annotate", `+${RX + 40}+60`, "STELLAR RAVEN",
  "-font", MONO, "-pointsize", "19", "-fill", "#9aa890", "-annotate", `+${RX}+170`, "REMOTE MCP SERVER",
  "-font", MONO, "-pointsize", "19", "-fill", "#ff5500", "-annotate", `+${RX + 240}+170`, "LIVE",
  "-font", SERIF, "-weight", "700", "-pointsize", "96", "-fill", "#eef0e2", "-annotate", `+${RX}+270`, "Stellar",
  "-font", SERIF, "-weight", "700", "-pointsize", "96", "-fill", "#ff5500", "-annotate", `+${RX}+370`, "Raven",
  "-font", SANS, "-weight", "400", "-pointsize", "25", "-fill", "#eef0e2", "-annotate", `+${RX}+440`, "One endpoint, two tools —",
  "-font", SANS, "-weight", "400", "-pointsize", "25", "-fill", "#eef0e2", "-annotate", `+${RX}+476`, "all of Stellar. No keys, no glue.",
  "-font", MONO, "-pointsize", "21", "-fill", "#ff5500", "-annotate", `+${RX}+552`, "raven.stellar.buzz/mcp",
  "-resize", "1200x630!", "-strip", p("og_final.png")]);

const b64 = readFileSync(p("og_final.png")).toString("base64");
const out =
  `// AUTO-GENERATED by scripts/gen-og.mjs — do not hand-edit.\n` +
  `// OG/social preview image (1200x630 PNG) served at /og.png, mirroring the\n` +
  `// landing hero (Bayer-dithered globe + editorial IBM Plex title).\n` +
  `export const OG_PNG_BASE64 =\n  "${b64}";\n`;
writeFileSync(join(root, "src", "og.ts"), out);
console.log(`wrote src/og.ts (${b64.length} b64 chars)`);
